sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: true
  exasolDbVersions:
    - "2026.1.2" # Latest
    - "2025.1.16" # Latest LTS
    - "8.29.13" # Latest 8.x
