<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.exasol</groupId>
    <artifactId>athena-virtual-schema-ci-isolation</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Athena Virtual Schema CI Isolation</name>
    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <aws.cdk.version>2.269.0</aws.cdk.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>software.amazon.awscdk</groupId>
            <artifactId>aws-cdk-lib</artifactId>
            <version>${aws.cdk.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <configuration>
                    <mainClass>com.exasol.athena.ciisolation.AthenaFixtureApp</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
